version: '3.9'
services:
    gofermart_db:
      container_name: gofermart_db
      image: postgres
      build:
        context: ./docker/db
        args:
          POSTGRES_DB: ${DATABASE_NAME}
      ports:
        - "${DATABASE_PORT}:5432"
      environment:
        POSTGRES_USER: ${DATABASE_USER}
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        POSTGRES_DB: ${DATABASE_NAME}